global_config:
  aws_access_key: hello123
  aws_secret_key: hello23456
cloud_provider:
  - name: aws
    regions:
      - name: us-west-1
        vpcs:
          num: 1
          instances:
            cloudInfo:
              availability_zone: a
              operating_system: rhel75
              instance_type: t2.xlarge
